### ISSUE TITLE
How to remove indent in bibiliography?

### ISSUE THREAD

**Issue by izCACI** [Docear/Docear4Word#36]
I am using Docear with Word 2007 to create a bibliography in the APA6 style. When I generate the bibliography, each entry has an indent on the left (shown by the red circles in the attachment). How can I get rid of these indents so then lines 2, 3 etc of each entry start at the same point as line 1? Thx
![indent](https://cloud.githubusercontent.com/assets/1793842/6611790/93ba7e2e-c847-11e4-86df-55b0d5dc36aa.jpg)

**Comment by faph** [comment]
I don't think GitHub Issues are for questions by the way.

But what you're looking for is editing the relevant `.csl` file in `c:\ProgramData\Docear4Word\Styles`.

Then look for this: `<bibliography hanging-indent="true" ...`

**Comment by izCACI** [comment]
Thanks you it worked
